new file:   .DS_Store
datacommonsorg/data pull request #716
Opened 2022-07-05 14:42 UTC by naizambhavani

new file:   scripts/.DS_Store
	new file:   scripts/eurostat/.DS_Store
	new file:   scripts/eurostat/health_determinants/.DS_Store
	new file:   scripts/eurostat/health_determinants/common/__pycache__/download.cpython-310.pyc
	new file:   scripts/eurostat/health_determinants/common/__pycache__/replacement_functions.cpython-310.pyc
	new file:   scripts/eurostat/health_determinants/common/denominator_mcf_generator.py
	new file:   scripts/eurostat/health_determinants/common/download.py
	new file:   scripts/eurostat/health_determinants/common/replacement_functions.py
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/.DS_Store
new file:   scripts/eurostat/health_determinants/fruits_vegetables/download_input_files.py
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/.DS_Store
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_de7.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_de8.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_fv1b.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_fv1c.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_fv1d.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_fv1e.tsv
	new file:   scripts/eurostat/health_determinants/fruits_vegetables/input_files/hlth_ehis_fv1i.tsv

2022-07-22 11:55 UTC, AravindhVenkatesh requested changes

2022-07-22 11:55 UTC, AravindhVenkatesh commented on scripts/eurostat/health_determinants/fruits_vegetables/download_input_files.py
> +    ]
INPUT_URLS =  ['https://ec.europa.eu....' + file for file in files]
where files is a list of files to be downloaded

2022-07-22 11:55 UTC, AravindhVenkatesh commented on scripts/eurostat/health_determinants/fruits_vegetables/preprocess.py
> +# Copyright 2022 Google LLC
Please rename this file.
preprocess.py -> process.py

2025-05-12 07:56 UTC, hareesh-ms commented
This PR is superseded. The import refresh and auto-refresh configuration are complete in another PR.

2025-05-12 07:56 UTC, closed without merging